# Generated by Django 2.2.24 on 2021-10-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=24)),
                ('sex', models.CharField(default=0, max_length=1)),
                ('address', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
