# Generated by Django 2.2.6 on 2022-03-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=50)),
                ('publish', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('img_url', models.CharField(max_length=150)),
                ('pub_data', models.DateField()),
                ('priice', models.FloatField()),
            ],
            options={
                'verbose_name': '书籍信息',
                'verbose_name_plural': '书籍信息',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='stu',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=24)),
                ('sex', models.CharField(default=0, max_length=1)),
                ('address', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'students',
            },
        ),
    ]
